version: "3"

tasks:
  default:
    desc: "Build the app"
    cmds:
      - echo "Build task executed"

  redis-typesense:
    desc: "Run Redis and Typesense services"
    cmds:
      - echo "Starting development environment..."
      - docker compose -f docker-compose.dev.yaml down
      - docker compose -f docker-compose.dev.yaml up -d redis typesense

  server:
    desc: "Server runner"
    deps: [redis-typesense]
    cmds:
      - go run ./cmd migrate up
      - echo "Migration completed and apply seed data if necessary"
      - go run ./cmd start

  workers:
    desc: "Workers runner"
    deps: [redis-typesense]
    cmds:
      - go run ./cmd start

  rebase-remote:
    desc: "Update Go module dependencies"
    cmds:
      - git remote add upstream git@github.com:blnkfinance/blnk.git
      - echo git remote -v
      - git fetch upstream
      - git checkout main
      - git rebase upstream/main

  docker:
    desc: "deploy blnk petropix QAS"
    dotenv: [".env.qas"]
    cmds:
      - echo "Starting development environment..."
      - docker compose -f docker-compose.dev.yaml down
      - echo "Building development environment without cache..."
      - docker compose -f docker-compose.dev.yaml build --no-cache
      - echo "Bringing up development environment..."
      - docker compose -f docker-compose.dev.yaml up

  deploy_qas:
    desc: "deploy blnk petropix QAS"
    dotenv: [".env.qas"]
    cmds:
      - cmd: docker run --privileged --rm tonistiigi/binfmt --install all
        platforms: [linux]
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $URL_ECR
      - docker buildx build --build-arg APP_ENV=$APP_ENV --platform linux/arm64 --rm --push -t $URL_ECR/$REPO_ECR:$VERSION-$APP_ENV .

  deploy_prd:
    desc: "deploy blnk petropix PRD"
    dotenv: [".env.prd"]
    cmds:
      - cmd: docker run --privileged --rm tonistiigi/binfmt --install all
        platforms: [linux]
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $URL_ECR
      - docker buildx build --build-arg APP_ENV=$APP_ENV --platform linux/arm64 --rm --push -t $URL_ECR/$REPO_ECR:$VERSION-$APP_ENV .
